# Data Preprocessing Tools

## Importing the libraries

In [15]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [16]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

In [17]:
print(X)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0


In [18]:
print(y)

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


## Taking care of missing data

In [19]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan , strategy= 'mean')
imputer.fit(X.iloc[:, 1:3])
X.iloc[:,1:3] = imputer.transform(X.iloc[:,1:3])

In [20]:
print(X)

   Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000


In [21]:
## ENCODING

### Encoding the Independent Variable

In [22]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
X = np.array(ct.fit_transform(x))

In [23]:
print(X)

[[0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  4.40000000e+01 7.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  2.70000000e+01 4.80000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  3.00000000e+01 5.40000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  3.80000000e+01 6.10000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  4.00000000e+01 6.37777778e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  3.50000000e+01 5.80000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  3.87777778e+01 5.20000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  4.80000000e+01 7.90000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  5.00000000e+01 8.30000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  3.70000000e+01 6.70000000e+04]]


### Encoding the Dependent Variable

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [25]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [27]:
print(X_train)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  3.87777778e+01 5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  4.00000000e+01 6.37777778e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  4.40000000e+01 7.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  3.80000000e+01 6.10000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  2.70000000e+01 4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  4.80000000e+01 7.90000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  5.00000000e+01 8.30000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  3.50000000e+01 5.80000000e+04]]


In [28]:
print(X_test)

[[1.0e+00 0.0e+00 1.0e+00 0.0e+00 3.0e+01 5.4e+04]
 [0.0e+00 1.0e+00 0.0e+00 0.0e+00 3.7e+01 6.7e+04]]


In [29]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [30]:
print(y_test)

[0 1]


## Feature Scaling

In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [32]:
print(X_train)

[[ 1.          0.          0.          1.29099445 -0.19159184 -1.07812594]
 [ 1.          0.          1.         -0.77459667 -0.01411729 -0.07013168]
 [ 0.          1.          0.         -0.77459667  0.56670851  0.63356243]
 [ 1.          0.          0.          1.29099445 -0.30453019 -0.30786617]
 [ 1.          0.          0.          1.29099445 -1.90180114 -1.42046362]
 [ 0.          1.          0.         -0.77459667  1.14753431  1.23265336]
 [ 1.          0.          1.         -0.77459667  1.43794721  1.57499104]
 [ 0.          1.          0.         -0.77459667 -0.74014954 -0.56461943]]


In [33]:
print(X_test)

[[ 1.          0.          1.         -0.77459667 -1.46618179 -0.9069571 ]
 [ 0.          1.          0.         -0.77459667 -0.44973664  0.20564034]]
